// The "mAIestro Code" wordmark: outlined SVG (generated by
// scripts/wordmark/build_wordmark.py) rather than live text, so its serifed I
// can't be read as an l and it looks the same on macOS and Windows. It sizes in
// `em` and sits on the text baseline, so it drops into a heading or a sentence
// and takes that text's size and color; the AI takes `--accent` (see
// `.wordmark` in styles.css). The SVG carries role="img" and the aria-label
// "mAIestro Code", so screen readers still read the name.

import WordmarkSvg from "../icons/wordmark.svg?react";

export function Wordmark() {
  return <WordmarkSvg className="wordmark" />;
}
